CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT PRIMARY KEY,
  mandatory_percent DOUBLE PRECISION NOT NULL DEFAULT 6,
  savings DOUBLE PRECISION NOT NULL DEFAULT 0,
  status_chat_id BIGINT,
  status_message_id BIGINT
);
CREATE TABLE IF NOT EXISTS months (
  user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  month DATE NOT NULL,
  budget DOUBLE PRECISION NOT NULL DEFAULT 0,
  spent DOUBLE PRECISION NOT NULL DEFAULT 0,
  rent DOUBLE PRECISION NOT NULL DEFAULT 0,
  saved DOUBLE PRECISION NOT NULL DEFAULT 0,
  PRIMARY KEY(user_id, month)
);
CREATE TABLE IF NOT EXISTS transactions (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_transactions_user_date ON transactions(user_id, created_at);
